on: push
jobs:
  build-d1_mini:
    name: Build binary for d1_mini
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/pip
              ~/.platformio/.cache
            key: ${{ runner.os }}-pio
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install PlatformIO Core
          run: pip install --upgrade platformio
      - uses: actions/setup-node@v3
        with:
          node-version: 14.3.0 # npm dependency resolution for esp8266 iot framework breaks with 16
      - name: Build PlatformIO project
        run: pio run -d ./ -e d1_mini
      - name: Adjust firmware filename
        run: mv .pio/build/d1_mini/firmware.bin firmware-d1_mini.bin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: firmware-d1_mini.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
