name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - uses: actions/setup-node@v3
      - name: Build PlatformIO Project
        run: pio run
      - name: Adjust firmware filename
        run: |
          cp .pio/build/d1_mini/firmware.bin firmware-d1_mini.bin
          mv .pio/build/d1_mini/firmware.bin ./binary/firmware-d1_mini.bin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: firmware-d1_mini.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
